import type { Lang } from './site';

/** Commercial facts reuse the existing offer. No invented outcomes or endorsements. */
const es = {
  skip: 'Saltar al contenido', nav: ['Trabajo', 'Servicios', 'Cómo trabajo', 'Presupuesto'], talk: 'Hablemos',
  role: 'Diseño y desarrollo web · España',
  hero: ['Tu negocio merece', 'una web', 'a su altura.'],
  intro: 'Diseño webs que explican lo que haces, transmiten confianza y ponen fácil dar el siguiente paso. Con trato directo, de la primera idea a la última página.',
  start: 'Cuéntame tu proyecto', work: 'Explora mi trabajo', from: 'Presupuesto a medida', time: 'Plazos acordados', quote: 'Todo por escrito',
  heroCaption: 'Una web real. Un negocio real.', heroNote: 'Fisioymés / diseño y desarrollo',
  pillars: ['Diseño a medida', 'Pensada para móvil', 'Trato directo conmigo', 'Para negocios de toda España'],
  workKicker: '01 / Trabajo seleccionado', workTitle: 'El diseño se demuestra.', workIntro: 'Una web tiene que encajar con el negocio que hay detrás. Aquí puedes ver las decisiones y explorar el resultado.',
  client: 'Proyecto de cliente', caseTitle: 'Fisioymés', caseLead: 'Menos búsqueda. Más claridad para pedir cita.',
  caseIntro: 'La clínica necesitaba una web más cómoda de usar en el móvil. Organicé la información alrededor de lo que busca un paciente y mantuve su sistema de reservas.',
  caseSteps: [
    ['El punto de partida', 'Demasiado texto y un recorrido largo en móvil para encontrar la información.'],
    ['La decisión', 'Lesiones en una rejilla, tratamientos en fichas y contenido en castellano y catalán.'],
    ['Lo que puedes comprobar', 'Una estructura más fácil de explorar, con acceso al sistema de citas que la clínica ya utilizaba.'],
  ],
  visit: 'Explorar el proyecto', caseTag: 'Fisioterapia · Web bilingüe',
  ideasKicker: 'Exploraciones de diseño', ideasTitle: 'Cada negocio tiene su carácter.', ideasIntro: 'Conceptos propios para explorar distintos sectores. Son propuestas de diseño, no encargos de clientes.', concept: 'Concepto', all: 'Ver todos los conceptos',
  servicesKicker: '02 / Lo que puedo hacer por ti', servicesTitle: 'De una buena idea a una web lista para abrir.',
  services: [
    ['Una web nueva', 'Para explicar bien tu negocio desde el primer día. Diseño a medida, contenido ordenado y un camino claro hasta el contacto.', 'Diseño y desarrollo', '/diseno-web/'],
    ['Un nuevo comienzo', 'Si tu web ya no te representa, reviso su estructura, diseño y experiencia móvil. Planificamos la transición con tus URLs y contenido actuales.', 'Rediseño web', '/rediseno-web/'],
    ['Que siga al día', 'Cambios de contenido, mantenimiento y preparación para buscadores. Añadimos lo que necesitas con su alcance y precio por escrito.', 'Mantenimiento y visibilidad', '/mantenimiento-web/'],
  ],
  processKicker: '03 / Así trabajamos', processTitle: 'Claro desde el primer mensaje.',
  process: [
    ['Hablamos de tu negocio', 'Me cuentas qué haces, a quién te diriges y qué necesita conseguir tu web.'],
    ['Cerramos el plan', 'Recibes alcance, precio y plazo por escrito. Sabes qué incluye antes de empezar.'],
    ['Diseño y construyo', 'Ordeno el contenido, diseño la web y la preparo para móvil y escritorio. Revisamos el resultado juntos.'],
    ['Revisamos y publicamos', 'Comprobamos contenido, enlaces y contacto. La web se publica cuando está lista y tienes claro cómo seguir.'],
  ],
  priceKicker: '04 / Presupuesto', priceTitle: 'Un presupuesto que empieza por escucharte.', priceIntro: 'Un cálculo automático no tiene sentido cuando cada negocio parte de un lugar distinto y necesita una combinación diferente de páginas, contenidos y funciones.',
  base: 'Propuesta a medida', priceNote: 'Primero hablamos; después recibes alcance, calendario y presupuesto por escrito.',
  includes: ['Las páginas que necesite tu proyecto', 'Diseño para móvil y escritorio', 'Una base preparada para crecer contigo', 'Formulario, WhatsApp y puesta en marcha'],
  estimate: 'Cuéntame qué necesitas',
  timeTitle: 'Primero, entender el proyecto', timeText: 'Hablamos de tu negocio, el punto de partida y lo que la web debe conseguir.',
  extraTitle: 'Después, concretar el alcance', extraText: 'Páginas, idiomas, reservas, migración o visibilidad: solo incluimos lo que tu proyecto necesita.',
  upkeepTitle: 'Por último, un presupuesto claro', upkeepText: 'Recibes alcance, calendario y coste por escrito antes de decidir, sin una cifra genérica que pueda llevar a error.',
  aboutKicker: '05 / Quién está detrás', aboutTitle: 'Soy Sergio. Y tu proyecto lo llevo yo.',
  aboutText: 'Diseño, desarrollo y hablo contigo. Una sola persona que conoce el proyecto de principio a fin, con comunicación directa y decisiones que puedes entender.',
  credentials: [
    ['Diseño y contenidos', 'Dos años en la web de la EEBE (UPC), con una beca de aprendizaje.'],
    ['Ciberseguridad', 'Un año en EY, trabajando en ciberseguridad.'],
    ['Ahora', 'Diseño web independiente para negocios y profesionales de toda España.'],
  ],
  buildTitle: 'Una base técnica que te simplifica las cosas.', buildText: 'Para webs corporativas, trabajo con páginas estáticas: carga ágil, menos mantenimiento y menos componentes expuestos. Las funciones externas, como formularios o reservas, se revisan aparte.',
  faqTitle: 'Antes de dar el paso.', faqKicker: 'Preguntas frecuentes',
  faqs: [
    ['¿Trabajas con negocios de cualquier parte de España?', 'Sí. Podemos definir el proyecto, revisar el diseño y preparar el lanzamiento a distancia. Trabajas directamente conmigo durante todo el proceso.'],
    ['¿Qué necesitas para empezar?', 'Una conversación para entender tu negocio y los textos, fotos o identidad que ya tengas. Si falta material, lo vemos antes de cerrar el alcance y el calendario.'],
    ['¿La web y el dominio son míos?', 'Sí. El dominio va a tu nombre y la web es tuya. Acordamos cómo administrarla y mantenerla cuando esté publicada.'],
    ['¿Qué ocurre si quiero cambiar algo después?', 'Puedes pedir cambios puntuales o un plan de mantenimiento. Te indico el alcance y el coste antes de hacerlos, porque no todos los cambios requieren el mismo trabajo.'],
    ['¿Puedes conservar mi dominio y mi web actual mientras trabajas?', 'Sí. La nueva web se prepara aparte. Revisamos el contenido, las direcciones y las redirecciones necesarias antes de sustituir la versión actual.'],
    ['¿Incluyes posicionamiento en Google?', 'La web se construye con una base técnica cuidada. La configuración de la ficha de Google y el servicio de posicionamiento se presupuestan aparte. No hay una garantía de posiciones: dependen también de la competencia y del contenido.'],
  ],
  contactKicker: 'El siguiente paso', contactTitle: ['Hagamos que tu web', 'esté a tu altura.'], contactText: 'Cuéntame a qué te dedicas, qué necesitas y si ya tienes web. Te respondo con una propuesta y un presupuesto por escrito, sin compromiso.',
  whatsapp: 'Hablemos por WhatsApp', email: 'Prefiero escribir un email', call: 'O llámame al',
  waText: 'Hola Sergio, me gustaría hablar contigo sobre una web para mi negocio.',
  footer: 'Diseño independiente. Trato directo. Toda España.', top: 'Volver arriba', language: 'Idioma', details: 'Más información',
};

const en: typeof es = {
  skip: 'Skip to content', nav: ['Work', 'Services', 'Process', 'Quote'], talk: 'Let’s talk',
  role: 'Web design & development · Spain', hero: ['Your business deserves', 'a website', 'to match.'],
  intro: 'I build websites that explain what you do, inspire confidence and make the next step easy. Work directly with me, from the first idea to the final page.',
  start: 'Tell me about your project', work: 'Explore my work', from: 'A tailored quote', time: 'An agreed schedule', quote: 'Everything in writing',
  heroCaption: 'A real website. A real business.', heroNote: 'Fisioymés / design & development',
  pillars: ['Custom design', 'Built for mobile', 'Work directly with me', 'For businesses across Spain'],
  workKicker: '01 / Selected work', workTitle: 'Let the design do the talking.', workIntro: 'A website should fit the business behind it. Explore the decisions and see the finished work.',
  client: 'Client project', caseTitle: 'Fisioymés', caseLead: 'Less searching. A clearer path to booking.',
  caseIntro: 'The clinic needed a website that was easier to use on a phone. I organised the information around what patients look for and kept their existing booking system.',
  caseSteps: [['The starting point', 'Too much text and a long mobile journey to find information.'], ['The decision', 'An injury grid, treatment cards and content in Spanish and Catalan.'], ['See for yourself', 'An easier structure to explore, with access to the booking system the clinic already used.']],
  visit: 'Explore the project', caseTag: 'Physical therapy · Bilingual website',
  ideasKicker: 'Design explorations', ideasTitle: 'Every business has a character.', ideasIntro: 'Independent concepts exploring different sectors. These are design proposals, not client commissions.', concept: 'Concept', all: 'See all concepts',
  servicesKicker: '02 / How I can help', servicesTitle: 'From a good idea to a website ready to open.',
  services: [['A new website', 'Present your business clearly from day one. Custom design, organised content and a clear route to getting in touch.', 'Design & development', '/diseno-web/'], ['A fresh start', 'If your website no longer represents you, I rethink its structure, design and mobile experience, and plan the transition around your current URLs and content.', 'Website redesign', '/rediseno-web/'], ['Keep it up to date', 'Content changes, maintenance and search preparation. We add what you need with a written scope and price.', 'Maintenance & visibility', '/mantenimiento-web/']],
  processKicker: '03 / The process', processTitle: 'Clear from the first message.',
  process: [['We talk about your business', 'Tell me what you do, who you serve and what your website needs to achieve.'], ['We agree on a plan', 'You get the scope, price and timeline in writing before work begins.'], ['I design and build', 'I organise the content and build for mobile and desktop. We review the result together.'], ['We check and launch', 'We review content, links and contact options. The site goes live when it is ready and you know what comes next.']],
  priceKicker: '04 / Your quote', priceTitle: 'A quote that starts by listening.', priceIntro: 'An automatic estimate makes little sense when every business starts somewhere different and needs its own mix of pages, content and features.',
  base: 'A tailored proposal', priceNote: 'We talk first; then you receive the scope, schedule and quote in writing.',
  includes: ['As many pages as your project needs', 'Mobile and desktop design', 'A foundation ready to grow with you', 'Contact form, WhatsApp and launch'],
  estimate: 'Tell me what you need',
  timeTitle: 'First, understand the project', timeText: 'We discuss your business, its starting point and what the website needs to achieve.',
  extraTitle: 'Then, define the scope', extraText: 'Pages, languages, bookings, migration or visibility: we only include what your project needs.',
  upkeepTitle: 'Finally, a clear quote', upkeepText: 'You receive scope, schedule and cost in writing before deciding, without a generic figure that could mislead you.',
  aboutKicker: '05 / The person behind it', aboutTitle: 'I’m Sergio. I take care of your project.',
  aboutText: 'I design, develop and talk with you. One person who knows your project from start to finish, with direct communication and decisions you can understand.',
  credentials: [['Design & content', 'Two years working on the EEBE (UPC) website through a student traineeship.'], ['Cybersecurity', 'One year working in cybersecurity at EY.'], ['Today', 'Independent web design for businesses and professionals across Spain.']],
  buildTitle: 'A technical foundation that keeps things simple.', buildText: 'For business websites, I build static pages: fast loading, less maintenance and fewer exposed components. External features, such as forms and bookings, are reviewed separately.',
  faqTitle: 'Before we get started.', faqKicker: 'Common questions',
  faqs: [['Do you work with businesses across Spain?', 'Yes. We can plan the project, review the design and prepare the launch remotely. You work directly with me throughout.'], ['What do you need to begin?', 'A conversation about your business and any text, photos or brand assets you have. We discuss missing materials before agreeing the scope and schedule.'], ['Will I own the website and domain?', 'Yes. The domain is registered in your name and the website is yours. We agree on administration and maintenance after launch.'], ['What if I need changes later?', 'You can request individual updates or a maintenance plan. I set out the scope and cost before making them, because not every change involves the same amount of work.'], ['Can I keep my domain and current website during the work?', 'Yes. The new site is built separately. We review content, URLs and any necessary redirects before replacing the current version.'], ['Is Google search optimisation included?', 'The site has a considered technical foundation. Google Business Profile setup and search optimisation are quoted separately. Rankings cannot be guaranteed; competition and content also matter.']],
  contactKicker: 'Your next step', contactTitle: ['Let’s build a website', 'that does you justice.'], contactText: 'Tell me what you do, what you need and whether you already have a website. I’ll reply with a proposal and a written quote, without obligation.',
  whatsapp: 'Let’s talk on WhatsApp', email: 'I’d rather send an email', call: 'Or call me on', waText: 'Hi Sergio, I would like to talk about a website for my business.',
  footer: 'Independent design. Direct communication. Across Spain.', top: 'Back to top', language: 'Language', details: 'More information (Spanish)',
};

const ca: typeof es = {
  skip: 'Saltar al contingut', nav: ['Treballs', 'Serveis', 'Com treballo', 'Pressupost'], talk: 'En parlem',
  role: 'Disseny i desenvolupament web · Espanya', hero: ['El teu negoci mereix', 'un web', 'a la seva altura.'],
  intro: 'Dissenyo webs que expliquen què fas, transmeten confiança i faciliten el següent pas. Amb tracte directe, de la primera idea a l’última pàgina.',
  start: 'Explica’m el teu projecte', work: 'Explora la meva feina', from: 'Pressupost a mida', time: 'Terminis acordats', quote: 'Tot per escrit',
  heroCaption: 'Un web real. Un negoci real.', heroNote: 'Fisioymés / disseny i desenvolupament',
  pillars: ['Disseny a mida', 'Pensat per a mòbil', 'Tracte directe amb mi', 'Per a negocis de tot Espanya'],
  workKicker: '01 / Treballs seleccionats', workTitle: 'El disseny es demostra.', workIntro: 'Un web ha d’encaixar amb el negoci que hi ha al darrere. Aquí pots veure les decisions i explorar el resultat.',
  client: 'Projecte de client', caseTitle: 'Fisioymés', caseLead: 'Menys cerca. Més claredat per demanar cita.',
  caseIntro: 'La clínica necessitava un web més còmode d’utilitzar al mòbil. Vaig organitzar la informació al voltant del que busca un pacient i vaig mantenir el seu sistema de reserves.',
  caseSteps: [['El punt de partida', 'Massa text i un recorregut llarg al mòbil per trobar la informació.'], ['La decisió', 'Lesions en una graella, tractaments en fitxes i contingut en castellà i català.'], ['El que pots comprovar', 'Una estructura més fàcil d’explorar, amb accés al sistema de cites que la clínica ja feia servir.']],
  visit: 'Explorar el projecte', caseTag: 'Fisioteràpia · Web bilingüe',
  ideasKicker: 'Exploracions de disseny', ideasTitle: 'Cada negoci té el seu caràcter.', ideasIntro: 'Conceptes propis per explorar diferents sectors. Són propostes de disseny, no encàrrecs de clients.', concept: 'Concepte', all: 'Veure tots els conceptes',
  servicesKicker: '02 / Què puc fer per tu', servicesTitle: 'D’una bona idea a un web llest per obrir.',
  services: [['Un web nou', 'Per explicar bé el teu negoci des del primer dia. Disseny a mida, contingut ordenat i un camí clar fins al contacte.', 'Disseny i desenvolupament', '/diseno-web/'], ['Un nou començament', 'Si el teu web ja no et representa, reviso l’estructura, el disseny i l’experiència mòbil. Planifiquem la transició amb els teus URL i continguts actuals.', 'Redisseny web', '/rediseno-web/'], ['Que segueixi al dia', 'Canvis de contingut, manteniment i preparació per als cercadors. Afegim el que necessites amb l’abast i el preu per escrit.', 'Manteniment i visibilitat', '/mantenimiento-web/']],
  processKicker: '03 / Així treballem', processTitle: 'Clar des del primer missatge.',
  process: [['Parlem del teu negoci', 'M’expliques què fas, a qui et dirigeixes i què ha d’aconseguir el teu web.'], ['Tanquem el pla', 'Reps l’abast, el preu i el termini per escrit. Saps què inclou abans de començar.'], ['Dissenyo i construeixo', 'Ordeno el contingut, dissenyo el web i el preparo per a mòbil i escriptori. Revisem el resultat junts.'], ['Revisem i publiquem', 'Comprovem contingut, enllaços i contacte. El web es publica quan està llest i tens clar com seguir.']],
  priceKicker: '04 / Pressupost', priceTitle: 'Un pressupost que comença per escoltar-te.', priceIntro: 'Un càlcul automàtic no té sentit quan cada negoci parteix d’un lloc diferent i necessita una combinació pròpia de pàgines, continguts i funcions.',
  base: 'Proposta a mida', priceNote: 'Primer en parlem; després reps l’abast, el calendari i el pressupost per escrit.',
  includes: ['Les pàgines que necessiti el teu projecte', 'Disseny per a mòbil i escriptori', 'Una base preparada per créixer amb tu', 'Formulari, WhatsApp i posada en marxa'],
  estimate: 'Explica’m què necessites',
  timeTitle: 'Primer, entendre el projecte', timeText: 'Parlem del teu negoci, el punt de partida i el que ha d’aconseguir el web.',
  extraTitle: 'Després, concretar l’abast', extraText: 'Pàgines, idiomes, reserves, migració o visibilitat: només incloem el que necessita el teu projecte.',
  upkeepTitle: 'Finalment, un pressupost clar', upkeepText: 'Reps l’abast, el calendari i el cost per escrit abans de decidir, sense una xifra genèrica que et pugui portar a error.',
  aboutKicker: '05 / Qui hi ha al darrere', aboutTitle: 'Soc en Sergio. I el teu projecte el porto jo.',
  aboutText: 'Dissenyo, desenvolupo i parlo amb tu. Una sola persona que coneix el projecte de principi a fi, amb comunicació directa i decisions que pots entendre.',
  credentials: [['Disseny i continguts', 'Dos anys al web de l’EEBE (UPC), amb una beca d’aprenentatge.'], ['Ciberseguretat', 'Un any a EY, treballant en ciberseguretat.'], ['Ara', 'Disseny web independent per a negocis i professionals de tot Espanya.']],
  buildTitle: 'Una base tècnica que et simplifica les coses.', buildText: 'Per a webs corporatius, treballo amb pàgines estàtiques: càrrega àgil, menys manteniment i menys components exposats. Les funcions externes, com formularis o reserves, es revisen a part.',
  faqTitle: 'Abans de fer el pas.', faqKicker: 'Preguntes freqüents',
  faqs: [['Treballes amb negocis de qualsevol lloc d’Espanya?', 'Sí. Podem definir el projecte, revisar el disseny i preparar el llançament a distància. Treballes directament amb mi durant tot el procés.'], ['Què necessites per començar?', 'Una conversa per entendre el teu negoci i els textos, fotos o identitat que ja tinguis. Si falta material, ho veiem abans de tancar l’abast i el calendari.'], ['El web i el domini són meus?', 'Sí. El domini va al teu nom i el web és teu. Acordem com administrar-lo i mantenir-lo quan estigui publicat.'], ['Què passa si vull canviar alguna cosa després?', 'Pots demanar canvis puntuals o un pla de manteniment. T’indico l’abast i el cost abans de fer-los, perquè no tots els canvis requereixen la mateixa feina.'], ['Pots conservar el meu domini i el meu web mentre treballes?', 'Sí. El web nou es prepara a part. Revisem el contingut, les adreces i les redireccions necessàries abans de substituir la versió actual.'], ['Inclous posicionament a Google?', 'El web es construeix amb una base tècnica cuidada. La configuració de la fitxa de Google i el servei de posicionament es pressuposten a part. No es poden garantir posicions: depenen també de la competència i del contingut.']],
  contactKicker: 'El següent pas', contactTitle: ['Fem que el teu web', 'estigui a la teva altura.'], contactText: 'Explica’m a què et dediques, què necessites i si ja tens web. Et responc amb una proposta i un pressupost per escrit, sense compromís.',
  whatsapp: 'Parlem per WhatsApp', email: 'Prefereixo escriure un correu', call: 'O truca’m al', waText: 'Hola Sergio, m’agradaria parlar amb tu d’un web per al meu negoci.',
  footer: 'Disseny independent. Tracte directe. Tot Espanya.', top: 'Tornar a dalt', language: 'Idioma', details: 'Més informació (castellà)',
};

export const studio: Record<Lang, typeof es> = { es, en, ca };
